version: '3.8'

services:
  app:
    build: 
      context: ./docker/dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /app
    ports:
      - "5006:5006"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    entrypoint: ["./docker/dev/entrypoint.sh", "./cmd/main.go", "grpc-server"]

  migrate:
    image: migrate/migrate
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    profiles:
      - donotstart

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - "5432"
